### ISSUE TITLE
Форма ввода проекта – Уточнить поведение системы при вводе недопустимого значения в поле "Название" 

### ISSUE THREAD

**Issue by AlenaDmukhouskaya** [AlenaDmukhouskaya/Firstproject#1]
В функциональных требованиях "Приложение для управления задачами" не описано поведение системы при вводе недопустимых значений в поле "Название".
Требуется уточнение.

**Comment by karpovichea** [comment]
1. В описании задачи лучше также конкретизировать, о какой форме идет речь, т.к. поле "Название" встречается на разных формах
2. Ответ на уточнение по требованиям: валидация всех полей происходит в момент сохранения, а не ввода данных на форме. Текст валидационного сообщения должен соответствовать ошибочной ситуации

**Comment by AlenaDmukhouskaya** [comment]
Ознакомилась с уточнением по заведённой задаче
