### ISSUE TITLE
Главное меню – Уточнить поведение системы при открытии форм "Список проектов", "Список задач", "Список сотрудников"

### ISSUE THREAD

**Issue by AlenaDmukhouskaya** [AlenaDmukhouskaya/Firstproject#2]
В функциональных требованиях "Приложение для управления задачами" не описано поведение системы при открытии форм "Список проектов", "Список задач", "Список сотрудников".
Требуется уточнение.

**Comment by karpovichea** [comment]
Просьба уточнить, что имеется в виду под "поведение системы при открытии форм". 
Например, при переходе к списку проектов должна отобразиться соответствующая форма. Элементы формы указаны в требованиях

**Comment by AlenaDmukhouskaya** [comment]
Под "поведением системы при открытии форм" имеется в виду: каким образом должны открываться формы "Список проектов", "Список задач", "Список сотрудников" из Главного меню (в открытой вкладке, в новой вкладке, в новом окне)?

**Comment by karpovichea** [comment]
Cтраницы с одного ресурса должны открываться в текущем окне

**Comment by AlenaDmukhouskaya** [comment]
С заведённой задачей на уточнение ознакомилась
